name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  Publish:
    name: Publish Next
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3
        with:
          fetch-depth: 0
      - name: Add TypeScript problem matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Use Node.js v16 with Yarn Registry
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build package
        run: yarn build
      - name: Install Git Cliff
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          curl -o ./git-cliff.tar.gz -sL \
              $(curl -sL \
                  -H "Authorization: bearer ${GITHUB_TOKEN}" \
                  -X POST \
                  --data '{"query":"query { repository(owner: \"orhun\", name: \"git-cliff\") { releases(last: 1) { nodes { releaseAssets(first: 20) { nodes { downloadUrl name }}}}}}"}' "https://api.github.com/graphql" |
              jq -cr '.data.repository.releases.nodes[0].releaseAssets.nodes[]? | select(.name | contains("x86_64-unknown-linux-gnu.tar.gz")).downloadUrl')

          tar -xzf ./git-cliff.tar.gz --wildcards "*git-cliff"
          mkdir -p ${HOME}/.local/bin
          mv git-cliff-*/git-cliff ${HOME}/.local/bin/git-cliff
          rm -r git-cliff-*

          echo $GITHUB_PATH

          echo "${HOME}/.local/bin" >> $GITHUB_PATH

          echo $GITHUB_PATH
      - name: Bump Version
        run: |
          echo $GITHUB_PATH
          yarn start --preid "next.$(git rev-parse --verify --short HEAD)" -v
      - name: Publish to Yarnpkg
        run: |
          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn npm publish --tag next || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Use Node.js v16 with GitHub Package Registry
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3
        with:
          node-version: 16
      - name: Publish to GitHub
        run: |
          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn config set npmPublishRegistry "https://npm.pkg.github.com"
          yarn npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
